# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dubbelblind
email: dubbelblind.podcast@gmail.com
description: "En podd om psykologisk vetenskap och de metoder som används för att ta reda på hur saker och ting faktiskt ligger till. De som gör podden heter Robin Fondberg och Martin Asperholm och de forskar inom psykologi."
subtitle: "En podd om psykologisk vetenskap."
lang: sv
author: Robin Fondberg och Martin Asperholm
copyright: "&#xA9; 2020"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dubbelblind.github.io" # the base hostname & protocol for your site

# Permalink
permalink: /:title.html

#Timezone
timezone: Europe/Stockholm

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']
